# Generated by Django 4.2.6 on 2023-10-13 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_managers_remove_user_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="total_reading_time_30_days",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="user",
            name="total_reading_time_7_days",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
